language: php

php:
  - 7.0.4
#  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --force
  - vendor/bin/codecept build

script: vendor/bin/codecept run